@echo off
echo [wumx] Starting development mode...
echo [wumx] Building main process...
call npx webpack --config webpack.main.config.js
echo [wumx] Starting renderer dev server...
start /B npx webpack serve --config webpack.renderer.config.js
echo [wumx] Waiting for dev server...
timeout /t 3 /nobreak >nul
echo [wumx] Launching Electron...
npx electron dist/main/main.js
